#!/usr/bin/env bash

D="\e[39m"
B="\e[96m"

IFS=" " read LOAD1 LOAD5 LOAD15 <<<$(cat /proc/loadavg | awk '{ print $1,$2,$3 }')

IFS=" " read USED FREE TOTAL <<<$(free -htm | grep "Mem" | awk {'print $3,$4,$2'})

DISKS=$(df -PTh | grep -v 'tmpfs\|loop\|s3fs' | awk -v red="$(tput setaf 1)" -v yellow="$(tput setaf 3)" -v reset="$(tput sgr0)" \
'NR>1 {
    if (int($6)>90) color=red; else if (int($6)>70) color=yellow; else color=""
    printf "%s\t%s\t%s(%s)%s\t%s\n", $4, $3, color, $6, reset, $7
}')


echo -e "
$D `cat /etc/*release | grep "PRETTY_NAME" | cut -d "=" -f 2- | sed 's/"//g'` `uptime -p`
$D LA...: $B$LOAD1$D, $B$LOAD5$D, $B$LOAD15$D
$D Disk.: $B$DISKS
$D Mem..: $B$USED$D used, $B$FREE$D free, $B$TOTAL$D total$D
\e[39m"
